### ISSUE TITLE
Linux installer fails on timer

### ISSUE THREAD

**Issue by Sanaki** [Insidious611/DancingMadFF6#95] opened 2020-01-08 15:44 UTC
Getting this error on attempting to run the Linux installer, with no other output:
`QObject::startTimer: Timers can only be used with threads started with QThread`

When invoked with python3 -v, these two lines precede that error.
```
import 'installermodule.operapage' # <_frozen_importlib_external.SourceFileLoader object at 0x7f2cc78c6668>
import 'installermodule.InstallWizard' # <_frozen_importlib_external.SourceFileLoader object at 0x7f2cd0e61d68>
```

**Comment by Dizzy611** [comment] 2020-01-11 21:09
Huh. Maybe a newer version of PyQt5 changed something.
I'll need to look into this more. Thanks for the report.

**Comment by Dizzy611** [comment] 2022-04-23 01:45
Have not been able to confirm this bug exists in testing, including on Python 3.10 with latest PyQt5. Closing as can't reproduce.

**Closed as completed by Dizzy611** 2022-04-23 01:45 UTC
Labels: bug, installer, blocking
