### ISSUE TITLE
Installer cannot download file

### ISSUE THREAD

**Issue by robvangeloven** [Insidious611/DancingMadFF6#116] opened 2022-12-27 11:57 UTC
Installer fails with cUrl error downloading / checksumming file 34/81

**Comment by Dizzy611** [comment] 2023-01-20 21:14
There should be a log (called dancing-mad-installer.log) in your Users directory (or /home/username on linux). If you could attach it for me I'd appreciate it.

It's useful primarily for letting me know which mirror you're having issues with. It's likely the Amazon mirror, one day the permissions just kind of broke.

**Comment by Dizzy611** [comment] 2023-06-09 06:31
Since you haven't commented with the log I need since posting the bug, I'm going to close this under the assumption this was a temporary mirror issue you've been unable to reproduce. Feel free to reopen when you have the log I need.

**Closed as completed by Dizzy611** 2023-06-09 06:31 UTC
