### ISSUE TITLE
Cut Songs Restoration mod (FFVI Special Tracks album)

### ISSUE THREAD

**Issue by edale2** [Insidious611/DancingMadFF6#55] opened 2017-12-16 14:44 UTC
Originally discussed over in #49.

Mod purpose: To add some of the 'unreleased" tracks from FFVI into the game without removing any of the existing tracks, utilizing the Dancing Mad MSU-1 mod.

Current form; Each of the 4 rooms in the Beginner's Classroom in Narshe plays a different track.

'Classroom' - Track 91 - Town 3
Environmental Science - Track 91 - Town 2
Battle Tactics - Track 92 - Troian Horse
Adv. Battle Tactics - Track 93 - Approaching Sentiment (non-vocal version) - LONG (3 min or so) loop, but beautiful song. Also a testament to how good I've gotten at looping, because I manage to perfectly loop a song that isn't supposed to be loopable (instruments change slightly throughout the song).

The only other track (besides the vocal version of Approaching Sentiment) is "Techno de Chocobo (Analogue Mix)"; which is not loopable.

https://mega.nz/#!qQJhSJjJ!OEevLxKKnziZgIn4ZPc1b0CuLJaYQawtntGeo9-L4a4

The IPS literally only mods 4 bytes (one byte for each song change), and can be applied either before or after the Dancing Mad patch. I can tell you the hex edits to the ROM, but have no clue how to do that with ASM.

If you don't feel like including this as an option in the installer, I'll just release it separately, So don't feel pressured to code this into the installer if you don't want to.

**Comment by edale2** [comment] 2017-12-16 21:13
I've not given up on actually adding the town themes to a tow or two, but until I can figure out that Pub thing, this is the best I could come up with.

**Comment by Dizzy611** [comment] 2017-12-17 02:13
To answer your question from issue #49, regarding this, I wrote you a little guide from a beginner's perspective on how to achieve what you asked for.

Wrote it in HTML in notepad++. No CSS here. Here's a link that you can read directly.
https://htmlpreview.github.io/?https://github.com/Insidious611/DancingMadFF6/blob/tracing-documentation/doc/tracingandsubroutines.html

**Comment by Dizzy611** [comment] 2017-12-17 02:18
I won't be able to respond to questions on this guide for a few hours at least, fwiw.

**Comment by edale2** [comment] 2017-12-17 03:02
Wow... I was just expecting a simple yes,no answer, lol.

So is C50182 the address I'd need to have a breakpoint set at? I can't just use a cheat search function to find the RAM address of the currently playing song like I found the RAM address for map ID, and monitor that address for changes to track 7/42/29, then traceback a step or three to see the command that made that change?

I'll experiment a bit, but at first glance this seems beyond my current skills...

Oh, and I noticed you called me "Dale" at the end, lol. edale isn't short for anything. I came up with the name many meay years ago in an elvish name generator, and really liked it. I use it for my handle pretty much everywhere now (or E'Dale on any DragonRiders of Pern related forums, lol).

**Comment by Dizzy611** [comment] 2017-12-17 05:02
You could do that, (monitor the address for the map id, or whatever RAM address you want, that is) yes. You can do any number of things, but the problem is whether or not what you find will be useful.

Unfortunately, the reason why I wrote that guide is that that kind of back-tracing, while complex, is definitely necessary to figure out what you're trying to figure out, at least if I've understand you correctly. :P 

Much of what I have done when setting this hack up to start with, investigating things, or tracking bugs involves setting breakpoints only to realize that the breakpoint is triggering too often to be useful. For example, triggering on write to $1301 (Song to play) is not helpful because this is also used for sound effects, even non-looping ones that don't otherwise hit my routine.

**Comment by Dizzy611** [comment] 2017-12-17 05:07
Oh, also useful but not covered in the guide: The memory editor (*Tools->Memory Editor*) will let you not only edit RAM but look at it, and even, if you tick auto-update, watch it change in real time. This is useful if you, say, set a breakpoint and want to see what an otherwise non-related area of memory is doing at the time of that breakpoint.

(Let's say, for example, you think you have found a breakpoint for the event signalling Shadow is in the Pub, you could then check "$1301" and see if "Shadow's Theme" is in it, and if not, step through to see when that changes.)

If you find a point in the code where you think I could "insert" some of my code to change something you need changed, point me to the address and I'll see if it can be done. Generally, this involves replacing an instruction with a *'jsl'* and duplicating what that instruction was doing right before the *'rtl'*, essentially returning to the running code having secretly done something behind the scenes.

I am considering trying to use Trace to map out all of bank 'c5', in hopes of finding exactly how volume changes are given to the SPC, as part of working on the fading.

**Comment by edale2** [comment] 2017-12-17 05:52
As far as triggering too often, could a breakpoint be set to only break when "07" is written to $1301?  Though in my case I'd be more interested in the commands right before "2A" is written to $1301 when entering the Pub (easy to check if every other map in South Figaro is set to a different song so won't trigger that break).

And I'm not sure inserting code like you described is necessary, shouldn't I just be able to replace the point in the code where 2A is written to $1301 with the song address that I want to use? (5B IIRC) which is literally a 1 byte hex-edit, if i can trace the point in the ROM to edit...

**Comment by Dizzy611** [comment] 2017-12-17 05:53
Yes, you could set such a breakpoint.

**Comment by Dizzy611** [comment] 2017-12-17 05:57
And yes, that would probably work assuming you've got the right
instruction. However, on my end to keep it clean (ie to not have to hex
edit the ROM every time i build a new patch) I'll have to at least
overwrite the instruction and its data, so that I have an assemblable line
of code. Something one-line like that might not need a subroutine though.

**Comment by Dizzy611** [comment] 2017-12-17 06:48
Actually, I was wrong on that last bit. The assembler I'm using allows me to define a byte or bytes as data at a certain location. I should be able to just do that to overwrite the bit in ROM you're trying to change, if it ends up being that simple. This would essentially be kind of like an automatic hex edit done by the assembler itself.

As an example, in case you were curious, if I wanted to replace bank 11 address FACE with the single byte "BD", I could do this

```
.BANK 11
.ORG $FACE
.SECTION "REPLACE" SIZE 1 OVERWRITE
.DB $BD
.ENDS
```

**Comment by edale2** [comment] 2017-12-17 07:39
As far as hex-editing every new patch, that's why I have the separate IPS that only overwrites the 4 needed bytes for the 4 song changes in this version.

For the option in the installer to add this, I was thinking a simple routine to apply this IPS onto the already MSU patched ROM, rather than incorporating it into the existing patch, it should be an optional addon, not a required part of the patch (music won't work in the areas my patch mods if the required PCM tracks aren't there).

And because of how minimalistic I managed to make that patch, it's compatible with any of the versions of the MSU patch, it shouldn't ever need an update once it's finished,

**Comment by edale2** [comment] 2017-12-17 07:43
Hmm... if it's that easy to code, here's the list of hex edits in the current patch:

2D9C84 -> 5B
2D9CA5 -> 5D
2D9CC6 -> 5C
2D9CE7 -> 5A

(IPS-Peek is such a useful little tool)

I have no idea what bank these addresses would be mapped to in RAM.

**Comment by edale2** [comment] 2017-12-17 12:23
Oh, the patch for this was made with a combination of Zone Doctor CE, IPS-Peek, IPS-Select, and Lunar IPS (LIPS).

Zone Doctor to make the audio changes.
IPS-Peek to examine the IPS generated by LIPS (and to notice a LOT more changes [40ish] were going on than should have been), as well as to identify the lines changed with the MSU mod so I could remove them from the final patch.
IPS-Select to patch only specific lines from the IPS onto a virgin copy of the ROM (just getting rid of the changes that were more than 4 bytes killed 20ish lines from the IPS).
And finally LIPS to generate the final IPS once I'd narrowed down the exact lines of the original IPS needed for the music changes.

Obviously there was extensive testing every step of the way to figure things out, but once I'd verified the first actual music change, locating the rest was childsplay.

**Comment by edale2** [comment] 2017-12-19 04:52
When setting a breakpoint at a write of '2A' to $1301, i get the following output in the disassembler after the break triggers from entering the Pub:
```
...
...
c0b780 lda $eb
c0b782 and #$7f
c0b784 sta $1301
c0b787 sta $1f80
c0b78a lda #$ff
c0b78c sta $1302
c0b78f lda $eb
c0b791 bpl $b797
...
...
```

Is that useful in tracking down where the command to play track 42 is coming from?

*edit- "c0b784 sta $1301" is the actual breakpoint.

**Comment by edale2** [comment] 2017-12-19 04:58
```
c09a99 lda $e1       [0000e1] A:0081 X:0000 Y:0000 S:15fb D:0000 DB:00 NvMxdIzc V:186 H:205 F:27
c09a9b bpl $9abe     [c09abe] A:0000 X:0000 Y:0000 S:15fb D:0000 DB:00 nvMxdIZc V:186 H:210 F:27
c09abe lda $e1       [0000e1] A:0000 X:0000 Y:0000 S:15fb D:0000 DB:00 nvMxdIZc V:186 H:215 F:27
c09ac0 and #$40               A:0000 X:0000 Y:0000 S:15fb D:0000 DB:00 nvMxdIZc V:186 H:220 F:27
c09ac2 beq $9ad0     [c09ad0] A:0000 X:0000 Y:0000 S:15fb D:0000 DB:00 nvMxdIZc V:186 H:223 F:27
c09ad0 lda $e1       [0000e1] A:0000 X:0000 Y:0000 S:15fb D:0000 DB:00 nvMxdIZc V:186 H:227 F:27
c09ad2 and #$20               A:0000 X:0000 Y:0000 S:15fb D:0000 DB:00 nvMxdIZc V:186 H:232 F:27
c09ad4 beq $9b1b     [c09b1b] A:0000 X:0000 Y:0000 S:15fb D:0000 DB:00 nvMxdIZc V:186 H:235 F:27
c09b1b ldy #$0005             A:0000 X:0000 Y:0000 S:15fb D:0000 DB:00 nvMxdIZc V:186 H:240 F:27
c09b1e lda [$e5],y   [caec52] A:0000 X:0000 Y:0005 S:15fb D:0000 DB:00 nvMxdIzc V:186 H:244 F:27
c09b20 sta $ef       [0000ef] A:00b3 X:0000 Y:0005 S:15fb D:0000 DB:00 NvMxdIzc V:186 H:255 F:27
c09b22 dey                    A:00b3 X:0000 Y:0005 S:15fb D:0000 DB:00 NvMxdIzc V:186 H:260 F:27
c09b23 lda [$e5],y   [caec51] A:00b3 X:0000 Y:0004 S:15fb D:0000 DB:00 nvMxdIzc V:186 H:263 F:27
c09b25 sta $ee       [0000ee] A:0081 X:0000 Y:0004 S:15fb D:0000 DB:00 NvMxdIzc V:186 H:273 F:27
c09b27 dey                    A:0081 X:0000 Y:0004 S:15fb D:0000 DB:00 NvMxdIzc V:186 H:278 F:27
c09b28 lda [$e5],y   [caec50] A:0081 X:0000 Y:0003 S:15fb D:0000 DB:00 nvMxdIzc V:186 H:281 F:27
c09b2a sta $ed       [0000ed] A:00b6 X:0000 Y:0003 S:15fb D:0000 DB:00 NvMxdIzc V:186 H:292 F:27
c09b2c dey                    A:00b6 X:0000 Y:0003 S:15fb D:0000 DB:00 NvMxdIzc V:186 H:297 F:27
c09b2d lda [$e5],y   [caec4f] A:00b6 X:0000 Y:0002 S:15fb D:0000 DB:00 nvMxdIzc V:186 H:300 F:27
c09b2f sta $ec       [0000ec] A:00c0 X:0000 Y:0002 S:15fb D:0000 DB:00 NvMxdIzc V:186 H:310 F:27
c09b31 dey                    A:00c0 X:0000 Y:0002 S:15fb D:0000 DB:00 NvMxdIzc V:186 H:315 F:27
c09b32 lda [$e5],y   [caec4e] A:00c0 X:0000 Y:0001 S:15fb D:0000 DB:00 nvMxdIzc V:186 H:318 F:27
c09b34 sta $eb       [0000eb] A:002a X:0000 Y:0001 S:15fb D:0000 DB:00 nvMxdIzc V:186 H:328 F:27
c09b36 dey                    A:002a X:0000 Y:0001 S:15fb D:0000 DB:00 nvMxdIzc V:186 H:333 F:27
c09b37 lda [$e5],y   [caec4d] A:002a X:0000 Y:0000 S:15fb D:0000 DB:00 nvMxdIZc V:186 H:336 F:27
c09b39 sta $ea       [0000ea] A:00f0 X:0000 Y:0000 S:15fb D:0000 DB:00 NvMxdIzc V:187 H:  6 F:27
c09b3b cmp #$31               A:00f0 X:0000 Y:0000 S:15fb D:0000 DB:00 NvMxdIzc V:187 H: 11 F:27
c09b3d bcs $9b42     [c09b42] A:00f0 X:0000 Y:0000 S:15fb D:0000 DB:00 NvMxdIzC V:187 H: 14 F:27
c09b42 cmp #$35               A:00f0 X:0000 Y:0000 S:15fb D:0000 DB:00 NvMxdIzC V:187 H: 19 F:27
c09b44 bcs $9b49     [c09b49] A:00f0 X:0000 Y:0000 S:15fb D:0000 DB:00 NvMxdIzC V:187 H: 22 F:27
c09b49 sec                    A:00f0 X:0000 Y:0000 S:15fb D:0000 DB:00 NvMxdIzC V:187 H: 26 F:27
c09b4a sbc #$35               A:00f0 X:0000 Y:0000 S:15fb D:0000 DB:00 NvMxdIzC V:187 H: 29 F:27
c09b4c rep #$20               A:00bb X:0000 Y:0000 S:15fb D:0000 DB:00 NvMxdIzC V:187 H: 32 F:27
c09b4e asl a                  A:00bb X:0000 Y:0000 S:15fb D:0000 DB:00 NvmxdIzC V:187 H: 37 F:27
c09b4f tax                    A:0176 X:0000 Y:0000 S:15fb D:0000 DB:00 nvmxdIzc V:187 H: 40 F:27
c09b50 lda $c098c4,x [c09a3a] A:0176 X:0176 Y:0000 S:15fb D:0000 DB:00 nvmxdIzc V:187 H: 43 F:27
c09b54 sta $2a       [00002a] A:b780 X:0176 Y:0000 S:15fb D:0000 DB:00 NvmxdIzc V:187 H: 52 F:27
c09b56 tdc                    A:b780 X:0176 Y:0000 S:15fb D:0000 DB:00 NvmxdIzc V:187 H: 59 F:27
c09b57 sep #$20               A:0000 X:0176 Y:0000 S:15fb D:0000 DB:00 nvmxdIZc V:187 H: 62 F:27
c09b59 jmp ($002a)   [c0002a] A:0000 X:0176 Y:0000 S:15fb D:0000 DB:00 nvMxdIZc V:187 H: 66 F:27
c0b780 lda $eb       [0000eb] A:0000 X:0176 Y:0000 S:15fb D:0000 DB:00 nvMxdIZc V:187 H: 75 F:27
c0b782 and #$7f               A:002a X:0176 Y:0000 S:15fb D:0000 DB:00 nvMxdIzc V:187 H: 80 F:27
c0b784 sta $1301     [001301] A:002a X:0176 Y:0000 S:15fb D:0000 DB:00 nvMxdIzc V:187 H: 83 F:27
c0b787 sta $1f80     [001f80] A:002a X:0176 Y:0000 S:15fb D:0000 DB:00 nvMxdIzc V:187 H: 89 F:27
c0b78a lda #$ff               A:002a X:0176 Y:0000 S:15fb D:0000 DB:00 nvMxdIzc V:187 H: 96 F:27
```

Here's a chunk of a trace log ending 2 lines after the breakpoint (over 1.5 million lines from the 2 seconds the trade was running as I entered the Pub...)

**Comment by edale2** [comment] 2017-12-21 07:17
ok, trying to track the instructions, not that I really understand what I'm finding...:

https://datacrystal.romhacking.net/wiki/Final_Fantasy_VI:ROM_map/Assembly_C0B#C0.2FB780_event_.23.24F0_:_play_song
```
C0/B780:	A5EB    	LDA $EB	
C0/B782:	297F    	AND #$7F
C0/B784:	8D0113  	STA $1301
```

And what's running right before that.
https://datacrystal.romhacking.net/wiki/Final_Fantasy_VI:ROM_map/Assembly_C09#C0.2F9B01_unknow
```
C0/9B49:	38      	SEC 			(from C0/9B44)
C0/9B4A:	E935    	SBC #$35       (event commands start at #$35)
C0/9B4C:	C220    	REP #$20      	(16 bit accum./memory)
C0/9B4E:	0A      	ASL A
C0/9B4F:	AA      	TAX
C0/9B50:	BFC498C0	LDA $C098C4,X  (Loads pointer for general action X)
C0/9B54:	852A    	STA $2A		(Stores it in $2A)
C0/9B56:	7B      	TDC 
C0/9B57:	E220    	SEP #$20      	(8 bit accum./memory)
C0/9B59:	6C2A00  	JMP ($002A)    (after the TAX, TDC SEP #$20 JMP ($98C4,X) would've worked)
```

**Comment by Dizzy611** [comment] 2017-12-21 16:58
Interesting. You're probably on the right track. Going to probably take a better look at what you've found after Christmas, see if I can't figure out what's going on.

At a quick glance, what you've found happening is that the 2A is being loaded from RAM address 0xEB in working memory (which, at a guess, was written to as part of an event script), ANDed with 0x7F (which just chops the first bit off, limiting the value to 128 or below. Good to know in general, this means that if this is the usual routine we can't use songs >128), and then stored in the "track to play" part of RAM.

**Comment by edale2** [comment] 2017-12-21 18:11
So I posted a thread over on romhacking.net about this a week or so ago asking for help. Not a word of help, or even a single response to the thread. http://www.romhacking.net/forum/index.php?topic=25397.0

A few hours ago I post that chunk of my tracelog, as well as those 2 chunks of the ROMmap.

Got this response just over an hour later (god is it ...fun... to convert the formatting between the 2 sites):

> The relevant code which loads the track number from ROM is this part of your first trace, just a bit further up:
>
>```
>c09b32 lda [$e5],y   [caec4e] A:00c0 X:0000 Y:0001 S:15fb D:0000 DB:00 nvMxdIzc V:186 H:318 F:27
>c09b34 sta $eb       [0000eb] A:002a X:0000 Y:0001 S:15fb D:0000 DB:00 nvMxdIzc V:186 H:328 F:27
>```
>
>In short, the data you want to change is at caec4e, i.e. aec4e in a headerless ROM.

And we have a solution! hex edited AEC4E, and it worked perfectly!

Now I'm trying to figure out how the guy figured it out, so I can duplicate the effort. and maybe revisit Town 2 in WoB Mobliz.

**Comment by Dizzy611** [comment] 2017-12-22 03:57
Awesome! Glad you found someone who knew what they were doing :p

**Comment by edale2** [comment] 2017-12-23 11:50
Note: Credit "mziab" on the romhacking.net forums for "help figuring out a tricky coding problem" in the readme when I finish this.

I've figured out how to track the hex location in the ROM myself now, and it takes less than 5 min to find and make each change.

Also Holy Crap! I did traced back and did this hex edit for WoB Mobliz in one building and it fixed the entire town!

This will require testing, possibly up to a full playthrough, to ensure none of these changes alter music anywhere I'm not intending.

Current Status:
South Figaro to Town 3 - Finished
WoB Mobliz to Town 2 - Finished
Nikeah to Troian Horse - Finished (Needs EXTENSIVE testing, every building, and the town map itself are "00" default tracks, and each one was pulling from a different ROM address, so it's very possible a different point in the game will still trigger track 42).
Classroom to Approaching Sentiment - Finished.

Yea, That's right, I'm fucking DONE (a good chunk of it being done while writing this, lol).

Now I just need to playtest the hell out of this. Probably going to alter a save file to get everyone hyper-max leveled, with Mog Charms equipped, so I only have to deal with event and boss battles.

**Comment by edale2** [comment] 2017-12-23 12:07
Oh, town/song selection was becasue:
South Figaro - Town 3 was a hard song to place, it didn't perfectly fit in on any town, but it felt most natural there.
WoB Mobliz - town 2 has a more adventurous feel to it, which I felt matched well with the only town on the Veldt.
Nikeah - When I figured out how to do the event scripted song selections, I thought that Troian Horse could _easily_ work as a town theme, and when I tried to think of a town to use, Nikeah was the OBVIOUS fit, to the point that I wonder if the song was originally written for Nikeah.
And I couldn't think of a single place in the game Approaching Sentiment would fit, so I stuck it in the classroom, because it's to good not to throw in.

**Comment by edale2** [comment] 2017-12-23 12:44
testing results;
Classroom at the very start of the game still plays Narshe's music.  Classroom's new music will only play on future visits. I'm ok with this.

Shadow's intro in South Figaro works as intended.

tested up to the first select a scenario decision. more testing to come.

**Comment by edale2** [comment] 2017-12-24 00:20
more testing (moogle charm's no encounters, everyone at lvl 99 with maxed stats, and the '~' key in BSNES to speed up gameplay, I'm testing hours 2-3 hours of stuff in about 1/2 an hour, lol):

Locke's scenario works as intended.

Once you hit Narshe in Terra/Edgar/Banon's scenario Classroom plays the altered song as I intended. Given how few people will actually go back to the classroom after the start of the game, only those actually looking will find this hidden gem of a song. I think I like that.

Now this is why I test EVERYTHING. watching the Serpent Trench scene in WoB Mobliz results in track 42 playing instead of the new track. Easy fix.

Serpent Trench bit fixed, hex location c66de (remember to add to IPS).

Nikeah in Sabin's scenario works as I intended.

tested to just after Thamasa, almost done with WoB.

*edit- patch updated with serpent trench scene fix.

WoR Mobliz 1st visit - music works as intended.

WoR Nikeah plays the original music, not the new track. as intended. South Figaro and the Classroom should be the only areas that still have new music in WoR.

WoR South Figaro plays new music like intended, including in the pub.

tested up to receiving the airship in WoR. Everything's working good so far. more testing tomorrow.

**Comment by edale2** [comment] 2017-12-25 04:10
The return of more testing:

Music works as intended in Mobliz during/after the retrieval of Terra.

I figure I can blow through most/all of the WoR stuff in an hour or two, whip up a readme, and have a Christmas release, wasn't even aiming for that, lol.

And wow, I apparently closed this by mistake days ago and didn't notice...

Classroom in WoR works as I intended.

**Comment by edale2** [comment] 2017-12-25 05:00
Would you believe I finished my testing at EXACTLY midnight...

Merry Christmas!

**Comment by edale2** [comment] 2017-12-25 07:11
https://mega.nz/#!DQAnBbgL!X-Xodf7JAmSPUHGqT_d_24ljPWVH_HyHWJTQYliUIIg

And here it is!

**Comment by edale2** [comment] 2017-12-27 07:52
https://mega.nz/#F!PJZg1IRb!kS3ECIgKhAkc-qHWkVGRAg

New link for the mod. Decided to rename it to "Cut Songs Restoration" to better reflect what the mod actually does.

**Comment by Dizzy611** [comment] 2017-12-30 09:55
Can I ask you to provide me with a blurb I can insert into the readme describing what your mod does in terms someone unfamiliar with this project can understand? 

I'll probably add it as a checkbox during the initial song selection bit (the ever growing army of radio buttons), but I want to document the option.

**Comment by edale2** [comment] 2017-12-30 16:07
Cut Songs Restoration: This option applies the optional Cut Songs Restoration mod, which seamlessly reintroduces 4 songs that were cut from FFVI in development, and later released in the FFVI Special Tracks Album, without removing any of the existing tracks. Mod created by edale, with help from Insidious661 and  mziab.

Is something like that what you were looking for?


Also: Grow my beloved army of options, we have enemies to slay, minds to corrupt, and laws of nature to pervert. I command you to GROW!!!! ;)

**Comment by Dizzy611** [comment] 2017-12-31 08:38
That's probably sufficient. I'll poke you if I think it needs editing once I'm at the point where I'm working on the readme again (won't be for a while, I'm still working on another project that I'm giving a lot of time to, and I also obviously still need to finish selecting tracks for Developer's Recommendation Mk 2, and complete the xmlification of the installer)

**Comment by edale2** [comment] 2018-01-02 14:33
Do you know if anything in the MSU patch touches on the bank of free space in the ROM at 14F606 - 14FFFF? I don't see anything in IPS-Peek, but asking makes for 'better safe than sorry'.

A day or two (hopefully, I'm not doing the actual work on this, just the testing and driving force, mostly done now, just working on a compatibility issue with TWUE 1.97a) and I should have something quite nice to add to the project. Will probably end up as a checkbox right next to this mod in the installer. ;)

**Comment by Dizzy611** [comment] 2018-01-11 17:37
I think you've already finished the "something quite nice" you were talking about, but no, I don't touch bank 14 at all.

**Comment by Dizzy611** [comment] 2018-01-24 08:40
As of d1f185c have added a check box for this into the installer. Haven't hooked it into any code yet though, that's my next step.

**Comment by Dizzy611** [comment] 2018-01-25 00:43
Code has been added, currently testing.

**Comment by Dizzy611** [comment] 2018-01-25 04:11
Added, tested, confirmed working! Closing this issue.

**Closed as completed by Dizzy611** 2018-01-25 04:11 UTC
Labels: enhancement, installer, patch
