### ISSUE TITLE
possible installer bug

### ISSUE THREAD

**Issue by edale2** [Insidious611/DancingMadFF6#57] opened 2017-12-30 00:27 UTC
Reported  on the Zelfix website here: https://www.zeldix.net/t1335p25-final-fantasy-3-dancing-mad-final-beta#23159

User with a SD2SNES rev.H with latest firmware downloaded the developer option settings in the installer.

Track 36 (SSC Battle Theme) wasn't normalized properly, and was too loud.

Grabbing a fresh copy manually from http://www.somebodyelsesproblem.org/ff6data/SSC/ff3-36.pcm fixed the problem.

Apparently he had the same problem with track 20 (OCR track 20), and grabbing a fresh copy fixed that too.

**Comment by Dizzy611** [comment] 2017-12-30 08:39
Huh. It may be that he ended up downloading from the wrong mirror and my mirror syncing scripts aren't working.

IE, he got specifically those tracks from one of the alternate mirrors and said alternate mirror has older tracks.

**Comment by Dizzy611** [comment] 2017-12-30 08:54
http://durandal.somebodyelsesproblem.org/ff6data/ is my alternate mirror (directory indexes are off, but you can pull the files, they're there), and afaict appears to be up to date. At least, md5summing SSC/ff3-36.pcm from there and from the main mirror at ash.somebodyelsesproblem.org produces identical results.

There was also the mirror provided by the guy from Qhimm, but I thought his mirror was down. If it's back up and serving old files, though, that would explain the issue.

...Nah, that's still showing up as down. Very odd. Well, it's not some sort of file corruption caused by an issue in the installer because that would result in a garbled mess, not a too-loud or older file...

I can't really attempt to reproduce this atm as we've a bandwidth cap here, it's the end of the month, and Dancing Mad's installer takes a lot of bandwidth to test.

My only other thought is maybe his ISP has a cache and they cached an older version of the file?

I didn't want to add an md5sum check to the end of the installer to guard against things like this because md5sums take a while (and would thus lengthen the already lengthy install process), but it might be worth doing just to prevent things like this happening again.

**Comment by Dizzy611** [comment] 2018-01-07 12:03
Closing this unable-to-reproduce as yeah, I can't figure out how this happened. Will consider the md5sum check as a possibility later.

**Closed as completed by Dizzy611** 2018-01-07 12:03 UTC
Labels: wontfix
